Parameters:
  TaskDefinitionArn:
    Type: String
  AlbStackName:
    Type: String
    Description: The name of the networking stack that these resources are put into.
  HostedZoneId:
    Type: String
    Description: name of domain stack
  ServiceName:
    Type: String
    Description: A human-readable name for the service.
  Priority:
    Type: Number
  Domain:
    Type: String
    Description: the domain of your app
  HealthCheckPath:
    Type: String
    Default: /
    Description: Path to perform the healthcheck on each instance.
  HealthCheckIntervalSeconds:
    Type: Number
    Default: 180
    Description: Number of seconds to wait between each health check.
  ContainerPort:
    Type: Number
    Default: 80
    Description: The port number the application inside the docker container is binding to.
  DesiredCount:
    Type: Number
    Default: 1
    Description: How many copies of the service task to run.
 
Resources:
  myLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref "ServiceName"
      RetentionInDays: 7
  
  Service:
    Type: 'AWS::ECS::Service'
    DependsOn: LoadBalancerRule
    Properties:
      ServiceName: !Ref ServiceName
      Cluster:
        'Fn::ImportValue': !Join
          - ':'
          - - !Ref AlbStackName
            - ClusterName
      LaunchType: FARGATE
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      DesiredCount: !Ref DesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - 'Fn::ImportValue': !Join
                - ':'
                - - !Ref AlbStackName
                  - ECSSecurityGroup
          Subnets:
            - 'Fn::ImportValue': !Join
                - ':'
                - - Network-Stack
                  - PublicSubnetOne
            - 'Fn::ImportValue': !Join
                - ':'
                - - Network-Stack
                  - PublicSubnetTwo
      TaskDefinition: !Ref TaskDefinitionArn
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
      EnableExecuteCommand: true
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 20
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: "200,301"
      TargetType: ip
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId:
        'Fn::ImportValue': !Join
          - ':'
          - - Vpc-Stack
            - Vpc
  LoadBalancerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      Conditions:
        - Field: host-header
          HostHeaderConfig:
            Values:
              - !Join
                - .
                - - www
                  - !Ref Domain
              - !Ref Domain
      ListenerArn:
        'Fn::ImportValue': !Join
          - ':'
          - - !Ref AlbStackName
            - HttpsPublicListener
      Priority: !Ref Priority
  DomainRecordSetGroup:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref Domain
          Type: A
          AliasTarget:
            DNSName:
              'Fn::ImportValue': !Join
                - ':'
                - - !Ref AlbStackName
                  - ElbDnsName
            HostedZoneId:
              'Fn::ImportValue': !Join
                - ':'
                - - !Ref AlbStackName
                  - ElbHostedZone
Outputs:
  TargetGroup:
    Description: The name of the ECS cluster
    Value: !Ref TargetGroup
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - TargetGroupArn
