


Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      
      
Outputs:
  Vpc:
    Description: Vpc Id
    Value: !Ref VPC
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", "Vpc"]]